<?php

namespace App\Filament\Clusters\Settings\Resources;

use App\Filament\Clusters\Settings;
use App\Filament\Clusters\Settings\Resources\SliderResource\Pages;
use App\Models\Product;
use App\Models\User;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Pages\SubNavigationPosition;
use Filament\Resources\Concerns\Translatable;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;
use TomatoPHP\FilamentCms\Filament\Resources\PostResource;
use TomatoPHP\FilamentCms\Models\Category;
use TomatoPHP\FilamentCms\Models\Post;
use TomatoPHP\FilamentCms\Services\FilamentCMSAuthors;
use TomatoPHP\FilamentCms\Services\FilamentCMSTypes;

class SliderResource extends PostResource
{
    use Translatable;
    protected static ?string $model = Post::class;
    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';
    protected static SubNavigationPosition $subNavigationPosition = SubNavigationPosition::Top;
    public static function getPluralLabel(): ?string
    {
        return "Sliders";
    }
    public static function getLabel(): ?string
    {
        return 'Slider';
    }

    public static function getNavigationLabel(): string
    {
        return 'Slider';
    }

    protected static ?string $cluster = Settings::class;

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->where('type' , 'slider'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Grid::make([
                    'default' => 1,
                    'sm' => 1,
                    'md' => 6,
                    'lg' => 12,
                ])
                    ->schema([
                        Forms\Components\Grid::make()
                            ->schema(
                                [
                                    Forms\Components\Section::make(trans('filament-cms::messages.content.posts.sections.post.title'))
                                        ->description(trans('filament-cms::messages.content.posts.sections.post.description'))
                                        ->schema([
                                            Forms\Components\Hidden::make('type')
                                                ->label("Type")
                                                ->required()
                                                ->default('slider'),
                                            Forms\Components\TextInput::make('title')
                                                ->label(trans('filament-cms::messages.content.posts.sections.post.columns.title'))
                                                ->afterStateUpdated( function(Forms\Get $get, Forms\Set $set){
                                                    if($get('type') !== 'open-source'){
                                                        $set('slug', Str::of($get('title'))->replace(' ', '-')->lower()->toString());
                                                    }
                                                })
                                                ->lazy()
                                                ->required(),
                                            Forms\Components\TextInput::make('slug')
                                                ->label(trans('filament-cms::messages.content.posts.sections.post.columns.slug'))
                                                ->required()
                                                ->maxLength(255),
                                            Forms\Components\MarkdownEditor::make('body')
                                                ->label(trans('filament-cms::messages.content.posts.sections.post.columns.body'))
                                                ->toolbarButtons([
                                                    'attachFiles',
                                                    'blockquote',
                                                    'bold',
                                                    'bulletList',
                                                    'codeBlock',
                                                    'heading',
                                                    'italic',
                                                    'link',
                                                    'orderedList',
                                                    'redo',
                                                    'strike',
                                                    'table',
                                                    'undo',
                                                ])
                                                ->columnSpanFull(),
                                        ])
                                        ->columns(2),
                                    Forms\Components\Section::make(trans('filament-cms::messages.content.posts.sections.seo.title'))
                                        ->description(trans('filament-cms::messages.content.posts.sections.seo.description'))
                                        ->schema([
                                            Forms\Components\TextInput::make('short_description')->label(trans('filament-cms::messages.content.posts.sections.seo.columns.short_description')),
                                            Forms\Components\Textarea::make('keywords')->autosize()->label(trans('filament-cms::messages.content.posts.sections.seo.columns.keywords')),
                                        ])
                                ]
                            )
                            ->columnSpan([
                                'sm' => 1,
                                'md' => 4,
                                'lg' => 8,
                            ]),
                        Forms\Components\Grid::make()
                            ->schema([
                                Forms\Components\Section::make(trans('filament-cms::messages.content.posts.sections.status.title'))
                                    ->description(trans('filament-cms::messages.content.posts.sections.status.description'))
                                    ->schema([
                                        Forms\Components\Select::make('categories')
                                            ->hidden(fn(Forms\Get $get)=> in_array($get('type'), ['page', 'builder']))
                                            ->relationship('categories', 'name')
                                            ->label(trans('filament-cms::messages.content.posts.sections.status.columns.categories'))
                                            ->createOptionForm([
                                                Forms\Components\TextInput::make('name')
                                                    ->label('Name')
                                                    ->required()
                                            ])
                                            ->createOptionUsing(function(array $data){
                                                $category = Category::query()->create([
                                                    'name' => $data['name'],
                                                    'slug' => Str::of($data['name'])->replace(' ', '-')->lower()->toString(),
                                                    'for' => 'post',
                                                    'type' => 'category'
                                                ]);

                                                return $category->id;
                                            })
                                            ->editOptionForm([
                                                Forms\Components\TextInput::make('name')
                                                    ->label('Name')
                                                    ->required()
                                            ])
                                            ->searchable()
                                            ->multiple()
                                            ->preload()
                                            ->options(fn(Forms\Get $get)=> Category::where('for', $get('type'))->where('type', 'category')->pluck('name', 'id')->toArray()),
                                        Forms\Components\Select::make('tags')
                                            ->hidden(fn(Forms\Get $get)=> $get('type') !== 'post')
                                            ->label(trans('filament-cms::messages.content.posts.sections.status.columns.tags'))
                                            ->searchable()
                                            ->multiple()
                                            ->preload()
                                            ->relationship('tags', 'name')
                                            ->createOptionForm([
                                                Forms\Components\TextInput::make('name')
                                                    ->label('Name')
                                                    ->required()
                                            ])
                                            ->createOptionUsing(function(array $data){
                                                $category = Category::query()->create([
                                                    'name' => $data['name'],
                                                    'slug' => Str::of($data['name'])->replace(' ', '-')->lower()->toString(),
                                                    'for' => 'post',
                                                    'type' => 'tag'
                                                ]);

                                                return $category->id;
                                            })
                                            ->editOptionForm([
                                                Forms\Components\TextInput::make('name')
                                                    ->label('Name')
                                                    ->required()
                                            ])
                                            ->options(Category::where('for', 'post')->where('type', 'tag')->pluck('name', 'id')->toArray()),
                                        Forms\Components\Toggle::make('is_published')
                                            ->label(trans('filament-cms::messages.content.posts.sections.status.columns.is_published'))
                                            ->default(true)
                                            ->required(),
                                        Forms\Components\DateTimePicker::make('published_at')
                                            ->hidden(fn(Forms\Get $get)=> in_array($get('type'), ['page', 'builder']))
                                            ->label(trans('filament-cms::messages.content.posts.sections.status.columns.published_at'))
                                            ->default(now()->format('Y-m-d H:i:s')),
                                    ]),
                                Forms\Components\Section::make(trans('filament-cms::messages.content.posts.sections.images.title'))
                                    ->description(trans('filament-cms::messages.content.posts.sections.images.description'))
                                    ->schema([

                                        Forms\Components\SpatieMediaLibraryFileUpload::make('feature_image')
                                            ->columnSpanFull()
                                            ->collection('feature_image')
                                            ->maxFiles(1)
                                            ->label(trans('filament-cms::messages.content.posts.sections.images.columns.feature_image'))
                                            ->label(trans('filament-ecommerce::messages.product.columns.feature_image')),
                                    ]),

                                Forms\Components\Section::make(trans('filament-cms::messages.content.posts.sections.meta.title'))
                                    ->visible(fn($record)=> $record && !empty($record->meta_url))
                                    ->description(trans('filament-cms::messages.content.posts.sections.meta.description'))
                                    ->schema([
                                        Forms\Components\TextInput::make('github_starts')
                                            ->disabled()
                                            ->numeric()
                                            ->label(trans('filament-cms::messages.content.posts.sections.meta.columns.github_starts')),
                                        Forms\Components\TextInput::make('github_watchers')
                                            ->disabled()
                                            ->numeric()
                                            ->label(trans('filament-cms::messages.content.posts.sections.meta.columns.github_watchers')),
                                        Forms\Components\TextInput::make('github_forks')
                                            ->disabled()
                                            ->numeric()
                                            ->label(trans('filament-cms::messages.content.posts.sections.meta.columns.github_forks')),
                                        Forms\Components\TextInput::make('downloads_total')
                                            ->disabled()
                                            ->numeric()
                                            ->label(trans('filament-cms::messages.content.posts.sections.meta.columns.downloads_total')),
                                        Forms\Components\TextInput::make('downloads_monthly')
                                            ->disabled()
                                            ->numeric()
                                            ->label(trans('filament-cms::messages.content.posts.sections.meta.columns.downloads_monthly')),
                                        Forms\Components\TextInput::make('downloads_daily')
                                            ->disabled()
                                            ->numeric()
                                            ->label(trans('filament-cms::messages.content.posts.sections.meta.columns.downloads_daily')),
                                    ]),
                            ])
                            ->columnSpan([
                                'sm' => 1,
                                'md' => 2,
                                'lg' => 4,
                            ]),
                    ])

            ]);
    }

    public static function table(Table $table): Table
    {
        $importActions = [];
        $table = $table
            ->headerActions($importActions)
            ->columns([
                Tables\Columns\SpatieMediaLibraryImageColumn::make('feature_image')
                    ->label(trans('filament-cms::messages.content.posts.sections.images.columns.feature_image'))
                    ->defaultImageUrl(fn(Post $post)=> 'https://ui-avatars.com/api/?name='.Str::of($post->slug)->replace('-','+').'&color=FFFFFF&background=020617')
                    ->square()
                    ->toggleable()
                    ->collection('feature_image'),
                Tables\Columns\TextColumn::make('title')
                    ->label(trans('filament-cms::messages.content.posts.sections.post.columns.title'))
                    ->description(fn(Post $post)=> Str::of($post->short_description)->limit(50))
                    ->toggleable()
                    ->searchable(),
                Tables\Columns\ToggleColumn::make('is_published')
                    ->toggleable()
                    ->sortable()
                    ->label(trans('filament-cms::messages.content.posts.sections.status.columns.is_published'))
                    ->onColor('success'),
                Tables\Columns\TextColumn::make('published_at')
                    ->toggleable()
                    ->label(trans('filament-cms::messages.content.posts.sections.status.columns.published_at'))
                    ->description(fn(Post $post)=> $post->published_at?->diffForHumans())
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([

                Tables\Filters\Filter::make('author_id')
                    ->label('Author')
                    ->form([
                        Forms\Components\Select::make('author_type')
                            ->label('Author Type')
                            ->options(count(FilamentCMSAuthors::getOptions()) ? FilamentCMSAuthors::getOptions()->pluck('name', 'model')->toArray() : [User::class => 'Users'])
                            ->afterStateUpdated( fn(Forms\Get $get, Forms\Set $set)=> $set('author_id', null))
                            ->live()
                            ->searchable(),
                        Forms\Components\Select::make('author_id')
                            ->label('Author')
                            ->hidden(fn(Forms\Get $get)=> !$get('author_type'))
                            ->disabled(fn(Forms\Get $get)=> !$get('author_type'))
                            ->options(fn(Forms\Get $get)=> $get('author_type') ? $get('author_type')::pluck('name', 'id')->toArray() : [])
                            ->searchable(),
                    ])
                    ->query(function (Builder $query, array $data){
                        return $query
                            ->when(
                                $data['author_type'],
                                fn (Builder $query, $type): Builder => $query->where('author_type', $type),
                            )
                            ->when(
                                $data['author_id'],
                                fn (Builder $query, $id): Builder => $query->where('author_id', $id),
                            );
                    }),

                Tables\Filters\Filter::make('published_at')
                    ->form([
                        Forms\Components\DatePicker::make('published_at')
                            ->label('Published At'),
                    ])
                    ->query(function (Builder $query, array $data){
                        return $query
                            ->when(
                                $data['published_at'],
                                fn (Builder $query, $publishedAt): Builder => $query->whereDate('published_at', $publishedAt),
                            );
                    }),
                Tables\Filters\Filter::make('is_published')
                    ->form([
                        Forms\Components\Toggle::make('is_published')
                            ->label('Published'),
                    ])
                    ->query(function (Builder $query, array $data){
                        return $query
                            ->when(
                                $data['is_published'],
                                fn (Builder $query, $isPublished): Builder => $query->where('is_published', (bool)$isPublished),
                            );
                    }),

                Tables\Filters\TrashedFilter::make()
            ])
            ->actions([
                /*
                Tables\Actions\ViewAction::make()
                    ->iconButton()
                    ->tooltip(__('filament-actions::view.single.label')),
                */
                Tables\Actions\EditAction::make()
                    ->iconButton()
                    ->tooltip(__('filament-actions::edit.single.label')),
                Tables\Actions\DeleteAction::make()
                    ->iconButton()
                    ->tooltip(__('filament-actions::delete.single.label')),
                Tables\Actions\ForceDeleteAction::make()
                    ->iconButton()
                    ->tooltip(__('filament-actions::force-delete.single.label')),
                Tables\Actions\RestoreAction::make()
                    ->iconButton()
                    ->tooltip(__('filament-actions::restore.single.label')),
            ])
            ->defaultSort('created_at', 'desc')
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                    Tables\Actions\ForceDeleteBulkAction::make(),
                    Tables\Actions\RestoreBulkAction::make(),
                    Tables\Actions\BulkAction::make('publish')
                        ->requiresConfirmation()
                        ->label(trans('filament-cms::messages.content.posts.sections.status.columns.is_published'))
                        ->icon('heroicon-o-check-circle')
                        ->action(function(Collection $records){
                            $records->each(fn($record) => $record->update(['is_published' => !$record->is_published]));

                            Notification::make()
                                ->title('Posts Published')
                                ->body('The selected posts have been published.')
                                ->success()
                                ->send();
                        })
                        ->deselectRecordsAfterCompletion(),
                    Tables\Actions\BulkAction::make('trend')
                        ->requiresConfirmation()
                        ->label(trans('filament-cms::messages.content.posts.sections.status.columns.is_trend'))
                        ->icon('heroicon-o-arrow-trending-up')
                        ->action(function(Collection $records){
                            $records->each(fn($record) => $record->update(['is_trend' => !$record->is_trend]));
                            Notification::make()
                                ->title('Posts Trended')
                                ->body('The selected posts have been trended.')
                                ->success()
                                ->send();
                        })
                        ->deselectRecordsAfterCompletion()
                ]),
            ]);



        return $table->recordUrl(fn(Post $record): string => Pages\ViewPost::getUrl([$record->id]));
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListSliders::route('/'),
            'create' => Pages\CreateSlider::route('/create'),
            'edit' => Pages\EditSlider::route('/{record}/edit'),
            'view' => Pages\ViewPost::route('/{record}/show'),
        ];
    }
}
